### ISSUE TITLE
Hub.State always null

### ISSUE THREAD

**Issue by bluewalk** [jlynch630/Harmony.NET#10]
Hub.State is always null, even after calling `hub.SyncConfigurationAsync();`. Hitting this when calling `hub.GetRunningActivity()`.

Background: simple console app to get the running activity and when my I switch my domotics to Night-Mode it should return the status and if different than -1 (Off) it should activate the -1 activity. Is it because the console app is not open for a long enough time to receive the `connect.statedigest?get` or `connect.statedigest?notify` commands?

**Comment by jlynch630** [comment]
Yeah I implemented this mostly halfway last night. There is a method like
`GetStateAsync` you can call which is separate from `SyncConfigurationAsync`

**Comment by bluewalk** [comment]
A brilliant, had to change 
```[JsonProperty("updates")]
public Dictionary<string, string> Updates { get; set; }
```
to 
```[JsonProperty("updates")]
public List<Dictionary<string, string>> Updates { get; set; }
```
in `StateDigest` to get it do deserialize though.

**Comment by jlynch630** [comment]
Interesting. Wonder why it didn't throw
