### ISSUE TITLE
WebSocketException during ConnectAsync

### ISSUE THREAD

**Issue by chrispi68** [jlynch630/Harmony.NET#12]
Hi,

when I call ConnectAsync(clientID) I get this exception:

System.Net.WebSockets.WebSocketException (0x80004005): 'Connection' header value 'upgrade,keep-alive' is invalid

Any Ideas? The Hub has upgraded a few days ago to the newest firmware. I am using .NET 4.6.1 with VS 2017.

UPDATE: .NET 4.7 is not working, but the same code works with .NET Core 2.1.

Best regards
Christoph

**Comment by jlynch630** [comment]
I'm working to try to switch to a different WebSocket library for .NET
Framework at the moment. You can see issues #3 and #2 for more info.

**Comment by chrispi68** [comment]
Thank you very much for this information!

Just a litte request on another issue: Can you ad a constructor to the DiscoverService so I can change the ListenPort to a different port than 5446? On my Home Server the port 5446 is already used.
