### ISSUE TITLE
GetRunningActivity should not return null

### ISSUE THREAD

**Issue by phen0mX** [jlynch630/Harmony.NET#14]
GetRunningActivity should not return null, because '-1' is a valid id and 'null' is not a valid activity.
It should instead return the 'PowerOff' activity or atleast something that represents the poweroff activity.

`return RunningActivityId != "-1" ? this.GetActivityById(RunningActivityId) : null;`

**Comment by jlynch630** [comment]
Done. Also added `IsPoweredOn` so there's still an easy way to check if the PowerOff activity is running
