### ISSUE TITLE
RFC: Exceptions

### ISSUE THREAD

**Issue by phen0mX** [jlynch630/Harmony.NET#17]
I am not here to critize in fact I want to thank everybody who contributed, especially jlynch.
But I would like to talk about the concept / usage of exceptions.
There are multiple ways to handle failure:

- Throwing Exceptions: 
Wich lead to quite unpredictable behaviour and seamingly 'random' crashes. 
Handling them usually results in splatterning try/catch all over the code as soon as a new exception surfaces or even preemptively. These usually just eat/disable the exception or rethrow it keeping the problem alive.
- Returning null:
This is better (imo) because it keeps the function working in all circumstances.
But the caller will have to have null checks everywhere or risk failing,
because those checks are not enforced. Also you won't get any kind of error information.
- Returning success (and result):
This could be a boolean or a tuple of boolean and result. Wich comunicates to the user that the function could fail and that the user should check before proceeding.
But it still looses the error info and does not enforce checking.
- Returning an option type (choice):
This is the way it is done in F#. It would return an option<'a> or nothing (not null).
It allows a function that will always work, does not require try/catch or null checking and
communicates clearly to the user. Still discards error info, but this can be added easily.
As far as I know there is no inbuild why to do this in c#. So It will have to be made. 

I am suggesting this because websockets seem to love throwing exceptions,
wich reduces reliability, usability and as an F# dev this is quite  annoying.

Is there a better c# way I am missing?
Any suggestions?

**Comment by phen0mX** [comment]
Maybe something like this: [https://github.com/mcintyre321/OneOf](url)

**Comment by jlynch630** [comment]
C# does have the concept of [`Nullable<T>`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/) or `T?` which I think is similar to what you are suggesting. With regards to exceptions, I am actually in full support of them. Exceptions to me indicate that something unexpected happened and needs to be communicated to the consumer. Take for example the following line:
```csharp
await Hub.SyncConfigurationAsync()
```
This command will actually update the internal state of the Hub. Often this line is left as is without any check of the return value. So if it returned anything that indicated failure, the user wouldn't know it. However, if the method threw an exception (which, funnily enough, it doesn't right now), the user would have to handle the failure of a synchronization **no matter how the method was called**. I think that's really important for making sure an error is communicated. Let me know your thoughts on this though.

**Comment by phen0mX** [comment]
> C# does have the concept of Nullable

Technically `Nullable<T>` is kind of what I am asking for. But it is limited to structs and has `Nullable<T>.Value`, wich allows unchecked access. So if what your are returning is not a struct it
 won't be obvious that it could be null and if the `Nullable<T>` is actually null accessing `Nullable<T>.Value` will fail.

> So if it returned anything that indicated failure, the user wouldn't know it. 

He would know by the return type e.g. Task<Option<HubSync>>
But you would be right in the case of just returning null.

> However, if the method threw an exception [..], the user would have to handle the failure of a synchronization no matter how the method was called

Which would be worse than it is right now. Because it takes the decision away from the user forcing his code to crash, unless he does the `try/catch` dance.
He won't even be aware of the possible failure until it fails (runtime) because the method signature does not tell him. (compile-time)

What I am arguing here is less about implementation but about concept.
It's the difference between `bool TryParse (string s, out int result)` and `int Parse (string s)`, while `out` is not a great way to do it, the signature of `TryParse` tells you what you need to know and it will always work. To achieve the same functionality with `Parse` you would have to wrap it in try/catch and the signature 'lies' to you. Telling you: if you give it a string it will give you an int. But sometimes it won't.
