### ISSUE TITLE
problem with method Connect

### ISSUE THREAD

**Issue by lucadibiagio** [jlynch630/Harmony.NET#2]
hello, when I try to connect to the hub i receive the following exception:

The 'Connection' header value 'upgrade,keep-alive' is invalid.

on this line:

HubConnetion.cs -->  await this.WebSocket.ConnectAsync(new Uri(FullUrl), CancellationToken.None);

with the following stack trace:

   at System.Net.WebSockets.ClientWebSocket.ValidateResponse(HttpWebRequest request, HttpWebResponse response)
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Harmony.HubConnection.<Connect>d__3.MoveNext()

have you any Idea of how can prevent this exception:

Harmony hub info:
CurrentFirmwareVersion 4.15.193

thank you,

luca

**Comment by jlynch630** [comment]
Hi. Unfortunately, this problem occurs with the .NET Framework implementation of the WebSocket protocol which throws an error because it receives a valid header value which it perceives to be invalid. This problem does not occur in .NET Core, which this library is designed for. If you can use .NET Core for your project, that would be best. However, if it's too late to switch, I have plans in place to switch to another WebSocket library for exactly this reason.

**Comment by lucadibiagio** [comment]
Thank you for your suggestion, I will switch to core,

Tx!

Luca

Excuse my typos...sent from mobile
+393351883549
________________________________
Da: John Lynch <notifications@github.com>
Inviato: giovedì, novembre 1, 2018 4:02 PM
A: jlynch630/Harmony.NET
Cc: Luca Di Biagio; Author
Oggetto: Re: [jlynch630/Harmony.NET] problem with method Connect (#2)

Hi. Unfortunately, this problem occurs with the .NET Framework implementation of the WebSocket protocol which throws an error because it receives a valid header value which it perceives to be invalid. This problemdoes not occur in .NET Core, which this library is designed for. If you can use .NET Core for your project, that would be best. However, if it's too late to switch, I have plans in place to switch to another WebSocket library for exactly this reason.
