### ISSUE TITLE
Switch to another WebSocket client library

### ISSUE THREAD

**Issue by jlynch630** [jlynch630/Harmony.NET#3]
The .NET WebSocket client implementation varies between the Framework and Core. In fact, the .NET Framework version is incompatible with this library.  WebSocketSharp seems promising. See issue #2

**Comment by sirmeili** [comment]
Any idea when you'll be doing this? I'm trying do do this in .net 4.5.2 and I hit the bad header issue. I may try and implement another websocket library on my own.

**Comment by jlynch630** [comment]
The WebSocket is fairly abstracted away from the client right now, so it shouldn't be too hard. I'll try a new branch with WebSocketSharp and see how I like that

**Comment by jlynch630** [comment]
Actually, WebSocketSharp is only available for .NET Framework, and the .NET Standard version (https://github.com/PingmanTools/websocket-sharp/) seems to be abandoned, so I'll need to find another library that is cross compatible

**Comment by sirmeili** [comment]
Hmm..Ok. I'll see if I can help you research tomorrow while I'm in my meetings :) (I work from home full time so call into all my meetings)

**Comment by bluewalk** [comment]
Seems like with the latest firmware upgrade (the one breaking XMPP) there are issues with the websocket, I'm getting:

```System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   ...

Inner Exception 1:
WebSocketException: The 'Connection' header value 'upgrade,keep-alive' is invalid.
```

**Comment by jlynch630** [comment]
Yeah unfortunately this is an issue with the .NET Framework's
implementation of System.Net.WebSockets, which looks at the Connection
header expecting "Upgrade" alone. See issue #2

**Comment by bluewalk** [comment]
I see, thanks. I have replaced the default websocket library with WebSocketSharp and it's working perfectly.

**Comment by sirmeili** [comment]
@bluewalk  Would you mind sharing how you incorporated WebSocketSharp into the WebSocketConnection object?

**Comment by sirmeili** [comment]
I have websocketsharp working, sort of. After about a minute of being connected, I always get this:

`12/19/2018 7:54:58 PM|Fatal|<>c__DisplayClass9.<ReadBytesAsync>b__8|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                               at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                               at WebSocketSharp.WebSocketFrame.<>c__DisplayClassa.<readHeaderAsync>b__9(Byte[] bytes)
                               at WebSocketSharp.Ext.<>c__DisplayClass9.<ReadBytesAsync>b__8(IAsyncResult ar)`

**Comment by jlynch630** [comment]
I saw the same issue on the official repo referenced when someone tried to
use WebSocketSharp with .NET Core. Is that how you're trying it?

**Comment by sirmeili** [comment]
My guess is that websocket-sharp does not periodically ping the server. I added timer to ping every 30 seconds an so far the connection is stable.

**Comment by sirmeili** [comment]
> I saw the same issue on the official repo referenced when someone tried to use WebSocketSharp with .NET Core. Is that how you're trying it?

I am using it with .net 4.5.2. I think it doesn't like how the "server" ends the connection. adding a ping every 30 seconds has solved it for now. My method is probably quick and dirty, but it's working for now (not sure System.Timers.Timer is the best way to handle that or not)

**Comment by bluewalk** [comment]
Sorry for the late reply, it was bedtime here ;-) Yes I'm using it on a 4.6.2 project and haven't run into the timeout, but that's probably because I'm using it in a simple fire-once console app.
There are other websocket libraries out there which might work better with .NET standard and core though.

For now I've forked your project and made the quick and dirty alterations in the `switch-websocket` branch: https://github.com/bluewalk/Harmony.NET/tree/switch-websocket

**Comment by jlynch630** [comment]
Tried using a different implementation of the `System.Net.Websockets` library. Try the new [branch](https://github.com/jlynch630/Harmony.NET/tree/new-websockets) and let me know if that works for you guys. Seems to work for me on .NET 4.6.2

**Comment by jlynch630** [comment]
@bluewalk the new branch looks nice, but again I'm just concerned about `WebSocketSharp` and .NET Core in general like you mentioned

**Comment by bluewalk** [comment]
@jlynch630 Yes, it wasn't the best solution to be honest. Will give your new branch a testrun and report back :)

**Comment by jlynch630** [comment]
Oh, right. I'll add that now

**Comment by bluewalk** [comment]
Will the new websockets branch make it to the master branch and will there be an updated nuget package soon? :)

**Comment by jlynch630** [comment]
Hopefully I can get that out with all the other features soon, need to do a
bit more testing!

**Comment by sirmeili** [comment]
So, wasn't sure where to put this, but I've fallen back to my XMPP implementation now that Logitech has added it back in and committed to keeping it there. I will move forward with web sockets, though be it slowly.

Note thought that Logitech has said that only XMPP should be used for this purpose and web sockets should not be used as they won't guarantee it will be around forever.

**Comment by jlynch630** [comment]
Got that @bluewalk, thanks. And yeah I mean great if they are, but I'm a little wary of Logitech saying that XMPP will be there forever @sirmeili. Anyway, I'm going to close this as a .NET framework compatible websocket library has been implemented and seems to work now.

**Comment by nevercast** [comment]
Did you end up using WebSocketSharp?

**Comment by jlynch630** [comment]
No actually I just switched to a different implementation of the
`System.Net.WebSockets` library available on nuget that worked for both
platforms. That's where the repository is at, but I haven't yet updated the
nuget package

**Comment by bluewalk** [comment]
I have actually switched to WebSocketSharp, the System.Net.Websockets solution simply didn't work properly. Throwing exceptions on random disconnects, causing my service to stop (as you cannot catch that one). I've replaced the logic with WebSocketSharp and it has been running for the past couple of months without any problems (you can see the repo here: https://github.com/bluewalk/Harmony.NET/tree/websocketsharp)
