### ISSUE TITLE
Unsolicited incoming messages

### ISSUE THREAD

**Issue by sirmeili** [jlynch630/Harmony.NET#5]
Is it possible to pick up on and react to incoming messages? For instance if I start an activity using my remote, Harmony.Net receives the messages and fires events based on them?

I had this implemented in my XMPP app for this, but I'm new to clientwebsocket and not sure how to just listen to incoming messages so I can react to them.

For instance be notified when an activity is started from the remote instead of from Harmony.net

**Comment by jlynch630** [comment]
Unfortunately, the WebSocket API doesn't send any messages when an event is started from an outside source.

Instead, the official app requests the current state of the Hub every 5 seconds or so. You can do this through the asynchronous `Hub.GetRunningActivity()` method, which returns either the active activity or null if there is none running.

**Comment by i8beef** [comment]
That is part of the reason my library does some of the stuff it does with TaskCompletionSource and background listeners (https://github.com/i8beef/HarmonyHub/blob/master/src/HarmonyHub/Client.cs). You might be able to shoehorn that in here with one SPECIFICALLY listening for Activity stuff since its the only real push based thing the Harmony does most people care about... if you wanted something more complete though, something like that might set you up for later if they ever add stuff.

A polling mechanism could work here as a stop gap though.

Just a heads up @jlynch630 in case you're wondering why the sudden interest in your library, Logitech knee-capped XMPP today, and your library seems to be last man standing for functional implementations in the world 😄

**Comment by sirmeili** [comment]
Maybe there is something up with ClientWebSocket then, If I connect to the WebSocket from a websocket tester, I definitely get updates from the hub in real time.

**Comment by sirmeili** [comment]
@i8beef I actually was starting work on grabbing events from the hub for the Home Automation side (Philips Hue, Nest, Harmony Extender). All those updates were also sent over the XMPP stream and I believe they are on the Web Socket implementation, but I haven't vetted that yet. I'm waiting until I get basic functionality back.

**Comment by jlynch630** [comment]
Really? I tried it with just logging packets from the app. Let me try with manually connecting to the websocket and get back to you.

**Comment by sirmeili** [comment]
@jlynch630 I am using the WebSocket Test Client chrome extension and just tested again to be sure. For instance when you start or stop an activity, you should get 4 messages giving you the different states (starting to change....changing, then one saying the activity is changed and another saying the state is changed). In my XMPP implementation I actually allow users to fire off events on the 3 states of an activity (and therefore 3 states of powering down)

I unfortunately can't use your library as is because I can't use a .net standard library in my .net project, but I would be more than willing to help you test and get it all working. If we can get it working, I'll likely create a .net 4.5.3 project based off of it (I'm restricted by the plugin framework my HA system uses)

**Comment by sirmeili** [comment]
You'll notice there are other messages as well. For instance, I get this message when I turn on one of my Hue Light strips via the Hub:

`{"type":"automation.state?notify","data":{"hue-[uniqueid]":{"color":{"mode":"ct","xy":{"y":0.3893,"x":0.4027},"temp":282,"hueSat":{"hue":9104,"sat":45}},"brightness":253,"on":true,"status":0}}}`

There are lots of messages like this. I've build up a library and if you break down he APK you'll see there is a good amount listed there (for both sending commands. like starting a sleep timer and receiving like the HA message above)

*I removed a unique id from that string as I'm not sure if it can link back to my hue account somehow

**Comment by i8beef** [comment]
That's a serious ask... but does make a case for a more robust background listener implementation. 

How many unique message formats are you aware of like that? Are they all "type" plus an arbitrary "data" parameter? Is it feasible to really Type all those out, or are you looking at a leaky abstraction that takes dynamics or something to support that?

**Comment by jlynch630** [comment]
Doing that right now actually!

Let me know if you have any comments on this:

I've decided to start a background loop which constantly listens for messages and raises different events based on the type parameter (which is always present, so far as I am aware).

That being said, it makes it much more difficult to have an `await this.ChangeChannel` unless using the ever-so-ugly event to async method conversion. However, if you think that you'd prefer
```csharp
await Hub.ChangeChannel("");
Hub.OnChannelChanged += ...
```
let me know.

**Comment by sirmeili** [comment]
They should be all Typed, but I think I was thinking more of the list of commands you can send The number of ones you can receive seems to be limited. However for the automation.state?notify, the "data" can change significantly depending on the device (Hue, Nest, Zigbee, etc), however his library would only have to fire that there was an automation event and pass on the data object and let the consumer handle identifying it.

**Comment by jlynch630** [comment]
@sirmeili The variety is why I avoided receiving automation states in the first place. I'll open a new issue for that though.

**Comment by sirmeili** [comment]
> @sirmeili The variety is why I avoided receiving automation states in the first place. I'll open a new issue for that though.

I would set that at a low priority for now. I would rather get the basic non HA stuff working first.

**Comment by i8beef** [comment]
> That being said, it makes it much more difficult to have an await this.ChangeChannel unless using the ever-so-ugly event to async method conversion. However, if you think that you'd prefer

Yeah, that's actually why I split FireAndForget and RequestResponse off separately and let the caller decide which they want. The trick is the TaskCompletionSource stuff I have in my lib to let the separate listener thread complete the awaited task for the RequestResponse ones. My implementation would have to expanded on to support more "unsolicited" responses than just activity updates though. But I think the pattern would actually serve you pretty well here...

On the other hand, bypassing it and just saying you won't do request / response is way easier than that.

**Comment by sirmeili** [comment]
The only time I think I might need request/response is when getting the config. I use this when adding a new hub to my plugin so I can create the devices in my HA software, but I'm sure there is a way around that that I'm not seeing. Otherwise for Activity start/stop, you don't really need it if you set up your event handlers. I normally don't care where the request started from, just that the activity is changing.

**Comment by sirmeili** [comment]
> The only time I think I might need request/response is when getting the config. I use this when adding a new hub to my plugin so I can create the devices in my HA software, but I'm sure there is a way around that that I'm not seeing. Otherwise for Activity start/stop, you don't really need it if you set up your event handlers. I normally don't care where the request started from, just that the activity is changing.

Now that I think of it, I won't need it on getting the config either. It will require a rework on how I handle that part of my code, but it would likely be better to just build/update devices when a new config is received no matter when.

**Comment by sirmeili** [comment]
> Pings are handled by the .NET client libary automatically. But yeah I'll just start with switching to events and will update those other methods later if need be.

On the topic of pings and not related to this issue, but is it possible to throw an event if the library loses connection with the hub for any reason (power outage, network issue, etc). I currently do this in the XMPP and use it to kick off a reconnect process.

And is there a place for discussions that are not necessarily "Issues"?

**Comment by jlynch630** [comment]
Yes. However, .NET pings anywhere between 30s and 2min so it might be a little delayed, but when it does happen I could start reconnecting and also add an event for it cause why not

**Comment by jlynch630** [comment]
I'm going to close this for now unless there are any more issues. It's pretty much implemented
