### ISSUE TITLE
Need either the Hub object or a UUID for each Event that is raised

### ISSUE THREAD

**Issue by sirmeili** [jlynch630/Harmony.NET#9]
Since I could be managing multiple hubs, I need a way to determine which hub raised the event when handling the event. You should either pass in the UUID or the Hub object itself.

**Comment by jlynch630** [comment]
Yeah, no worries. FYI, everything I just committed was mostly to save and is thus totally untested

**Comment by sirmeili** [comment]
Yeah, I'm fixing some stuff as I go along. Most of it works as is, I'm just hitting the stupid .net header bug with the clientwebsocket libaray on .net 4.5.2. I may try and do websocket-sharp to get it working. I think it will require a rewrite of only 2 of your files. I'm gonna save it for tomorrow night though as I got another long day tomorrow.
